name: "Hotfix Naming"
description: "Generate smart hotfix branch and names with suffix handling"
inputs:
  base_tag:
    description: "Base tag to create hotfix from"
    required: true
  hotfix_version:
    description: "Hotfix version number or string"
    required: true
outputs:
  hotfix_branch:
    description: "Generated hotfix branch name"
    value: ${{ steps.calculate.outputs.hotfix-branch }}
  hotfix_name:
    description: "Generated hotfix name"
    value: ${{ steps.calculate.outputs.hotfix-name }}
runs:
  using: "composite"
  steps:
    - name: Calculate hotfix names
      id: calculate
      shell: bash
      run: |
        # Smart branch naming logic inline (no external scripts needed)
        BASE_TAG="${{ inputs.base_tag }}"
        HOTFIX_VERSION="${{ inputs.hotfix_version }}"

        if [[ "$BASE_TAG" == *"-hotfix-"* ]]; then
          BASE_VERSION=$(echo "$BASE_TAG" | sed 's/-hotfix-.*$//')
          HOTFIX_BRANCH="hotfix/$BASE_VERSION-hotfix-$HOTFIX_VERSION"
          HOTFIX_NAME="$BASE_VERSION-hotfix-$HOTFIX_VERSION"
          echo "🔄 Base tag contains existing hotfix suffix, creating clean branch name"
          echo "   Original tag: $BASE_TAG → New branch: $HOTFIX_BRANCH"
        else
          HOTFIX_BRANCH="hotfix/$BASE_TAG-hotfix-$HOTFIX_VERSION"
          HOTFIX_NAME="$BASE_TAG-hotfix-$HOTFIX_VERSION"
          echo "✅ Creating standard hotfix branch: $HOTFIX_BRANCH"
        fi

        # Set outputs
        echo "hotfix-branch=$HOTFIX_BRANCH" >> $GITHUB_OUTPUT
        echo "hotfix-name=$HOTFIX_NAME" >> $GITHUB_OUTPUT

        # Set environment variables for subsequent steps (if GITHUB_ENV is available)
        if [[ -n "$GITHUB_ENV" ]]; then
          echo "HOTFIX_BRANCH=$HOTFIX_BRANCH" >> $GITHUB_ENV
          echo "HOTFIX_NAME=$HOTFIX_NAME" >> $GITHUB_ENV
        fi

        echo "Generated names:"
        echo "  Branch: $HOTFIX_BRANCH"
        echo "  Name: $HOTFIX_NAME"
