name: Deploy to Cloud Run Job

on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      metadata-file-path:
        required: true
        type: string
      job:
        required: true
        type: string
      workload-identity-provider:
        required: true
        type: string
      service-account:
        required: true
        type: string

jobs:
  deploy-to-cloud-run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ github.event.inputs.workload-identity-provider }}
          service_account: ${{ github.event.inputs.service-account }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          job: ${{ github.event.inputs.job }}
          region: ${{ github.event.inputs.region }}
          metadata: ${{ github.event.inputs.metadata-file-path }}

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
