name: Deploy to Cloud Run Job

on:
  workflow_call:
    inputs:
      workload-identity-provider:
        required: true
        type: string
      service-account:
        required: true
        type: string
      region:
        required: true
        type: string
      metadata-file-path:
        required: true
        type: string

jobs:
  deploy-to-cloud-run-job:
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Cloud Run YAML artifact
        uses: actions/download-artifact@v3
        with:
          name: cloudrun-yaml

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          region: ${{ inputs.region }}
          metadata: ${{ inputs.metadata-file-path }}
