name: Deploy to Cloud Run

on:
  workflow_call:
    inputs:
      workload-identity-provider:
        required: true
        type: string
      service-account:
        required: true
        type: string
      region:
        required: true
        type: string
      metadata-file-path:
        required: true
        type: string

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          region: ${{ inputs.region }}
          metadata: ${{ inputs.metadata-file-path }}

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
