name: Test

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
jobs:
  test:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 1

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - uses: buildjet/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: buildjet/cache@v4
        name: Setup pnpm cache
        with:
          node-version: 20
          path: |
            node_modules
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm lint
      - run: pnpm test:cov

      - name: Upload test coverage artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage
